### ISSUE TITLE
saving bug

### ISSUE THREAD

**Issue by Bobbbe** [esx-framework/esx_garage#11]
mileage and gas is not saved correctly, I leave the garage with 65% of the tank 4/5, i dont have any error in F8 or console server !
i'm use -

esx legacy 1.9.4
description 'Official ESX Garage System for ESX Legacy'
version '1.0'
legacyversion '1.9.1'

![image](https://user-images.githubusercontent.com/42454593/232909753-c220fe3f-f4b5-4637-a96c-58eeebf1f435.png)
![image](https://user-images.githubusercontent.com/42454593/232908968-c113144f-5690-44f7-bacd-e7602078f468.png)

**Comment by Bobbbe** [comment]
im on discord esx framework if you want see in direct i can share my screen for you, i'm Bobbber

**Comment by Gellipapa** [comment]
#38 I tested and works, close this issue.
